module.exports={
    USER_COLLECTION:'User',
    CATEGORY_COLLECTION:'Category',
    BRAND_COLLECTION:'Brand',
    PRODUCT_COLLECTION:'Product',
    ADMIN_COLLECTION:'admin',
    CART_COLLECTIONS:'Cart',
    ORDER_COLLECTION:'Order',
    BANNER_COLLECTION:'Banner'
}